# Generated by Django 3.1.2 on 2023-07-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='custormer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='style_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='tailor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
